import type {
  Board,
  Comment,
  FeedEntry,
  LifecycleRecord,
  Notice,
  Person,
  Project,
  ReleaseEnvironment,
  ReleaseRecord,
  ReleaseVersion,
  Sprint,
  TestCase,
  TestExecution,
  TestRun,
  TestSuite,
  WorkItem,
  WorkLog,
  TaskDependency,
} from "./domain";

export const people: Person[] = [
  { id: "p-lin", name: "林知夏", role: "项目经理" },
  { id: "p-xu", name: "许清和", role: "项目负责人" },
  { id: "p-zhou", name: "周衡", role: "开发" },
  { id: "p-han", name: "韩砺", role: "开发" },
  { id: "p-chen", name: "陈予安", role: "测试" },
  { id: "p-su", name: "苏晚", role: "设计" },
];

export const projects: Project[] = [
  {
    id: "pr-hc",
    key: "HC",
    name: "恒川研发主线",
    summary: "项目全生命周期：需求、任务、缺陷、迭代与版本在同一工作台流转。",
    leadId: "p-xu",
    memberIds: ["p-lin", "p-xu", "p-zhou", "p-han", "p-chen", "p-su"],
  },
  {
    id: "pr-pay",
    key: "PAY",
    name: "商户对账",
    summary: "对账差异、开票申请和回单核对。",
    leadId: "p-lin",
    memberIds: ["p-lin", "p-zhou", "p-chen"],
  },
  {
    id: "pr-ops",
    key: "OPS",
    name: "值班改进",
    summary: "把告警、交接和复盘从表格里收进迭代。",
    leadId: "p-han",
    memberIds: ["p-han", "p-su", "p-chen"],
  },
];

export const sprints: Sprint[] = [
  {
    id: "sp-24",
    projectId: "pr-hc",
    name: "Sprint 24",
    goal: "看板拖拽遵守真实状态机，事项详情分开评论和对象动态。",
    state: "active",
    start: "2026-09-22",
    end: "2026-10-10",
  },
  {
    id: "sp-25",
    projectId: "pr-hc",
    name: "Sprint 25",
    goal: "版本冻结后锁定范围，未完成事项留在待办。",
    state: "planned",
    start: "2026-10-13",
    end: "2026-10-24",
  },
  {
    id: "sp-23",
    projectId: "pr-hc",
    name: "Sprint 23",
    goal: "把需求、任务、缺陷收成同一套事项键。",
    state: "closed",
    start: "2026-09-08",
    end: "2026-09-19",
  },
  {
    id: "sp-pay",
    projectId: "pr-pay",
    name: "Sprint 8",
    goal: "差异单可以指派并进入验证。",
    state: "active",
    start: "2026-09-28",
    end: "2026-10-09",
  },
];

export const versions: ReleaseVersion[] = [
  {
    id: "v-16",
    projectId: "pr-hc",
    name: "秋季基线",
    versionNumber: "1.6.0",
    versionType: "次版本",
    status: "RELEASED",
    plannedReleaseDate: "2026-09-19",
    description: "事项键、项目成员和基础列表。",
  },
  {
    id: "v-17",
    projectId: "pr-hc",
    name: "协作工作台",
    versionNumber: "1.7.0",
    versionType: "次版本",
    status: "TESTING",
    plannedReleaseDate: "2026-10-10",
    description: "看板、待办和事项详情。正在测试。",
  },
  {
    id: "v-18",
    projectId: "pr-hc",
    name: "发布门禁",
    versionNumber: "1.8.0",
    versionType: "次版本",
    status: "DEVELOPMENT",
    plannedReleaseDate: "2026-10-24",
    description: "版本冻结、范围锁定和发布说明。",
  },
  {
    id: "v-pay",
    projectId: "pr-pay",
    name: "对账九月",
    versionNumber: "0.9.0",
    versionType: "次版本",
    status: "DEVELOPMENT",
    plannedReleaseDate: "2026-10-09",
    description: "差异单闭环。",
  },
];

const item = (partial: WorkItem): WorkItem => partial;

export const items: WorkItem[] = [
  item({
    id: "it-101",
    key: "HC-101",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Epic",
    taskType: null,
    defectType: null,
    severity: null,
    title: "工作项统一视图",
    description: "需求、任务和缺陷共用事项键、负责人和迭代，不再分成三套互不相通的表格。",
    priority: "HIGH",
    status: "IN_DEVELOPMENT",
    assigneeId: "p-lin",
    reporterId: "p-xu",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: null,
    storyPoints: 13,
    progress: 40,
    estimatedHours: null,
    tags: ["工作台"],
    createdAt: "2026-09-08T02:00:00.000Z",
    updatedAt: "2026-09-30T08:12:00.000Z",
  }),
  item({
    id: "it-102",
    key: "HC-102",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Epic",
    taskType: null,
    defectType: null,
    severity: null,
    title: "发布门禁",
    description: "版本进入冻结后，范围里的事项不能再悄悄加进来。发布说明只收录已完成项。",
    priority: "MEDIUM",
    status: "APPROVED",
    assigneeId: "p-han",
    reporterId: "p-xu",
    sprintId: "sp-25",
    versionId: "v-18",
    parentId: null,
    storyPoints: 8,
    progress: 0,
    estimatedHours: null,
    tags: ["版本"],
    createdAt: "2026-09-18T02:00:00.000Z",
    updatedAt: "2026-09-29T03:20:00.000Z",
  }),
  item({
    id: "it-128",
    key: "HC-128",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "看板拖拽必须走允许的状态流转",
    description: "从一列拖到另一列时，只在当前状态的可流转集合里找目标列对应的状态。找不到就弹回，并告诉操作者下一步能去哪。",
    priority: "HIGH",
    status: "IN_DEVELOPMENT",
    assigneeId: "p-zhou",
    reporterId: "p-lin",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-101",
    storyPoints: 5,
    progress: 0,
    estimatedHours: null,
    tags: ["看板"],
    createdAt: "2026-09-22T01:00:00.000Z",
    updatedAt: "2026-09-30T10:00:00.000Z",
  }),
  item({
    id: "it-131",
    key: "HC-131",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "事项详情把评论和对象动态分开",
    description: "评论是讨论，有自己的写模型。对象动态只读，来自已经发生的事实，不能在详情里编辑或补写。",
    priority: "HIGH",
    status: "REVIEW",
    assigneeId: "p-su",
    reporterId: "p-lin",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-101",
    storyPoints: 3,
    progress: 0,
    estimatedHours: null,
    tags: ["详情"],
    createdAt: "2026-09-23T02:10:00.000Z",
    updatedAt: "2026-09-30T06:40:00.000Z",
  }),
  item({
    id: "it-136",
    key: "HC-136",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "待办按迭代分组，未排期单独成组",
    description: "进行中的迭代放在最上面。规划中的迭代可以开始，但同一项目同时只能有一个进行中迭代。",
    priority: "MEDIUM",
    status: "DRAFT",
    assigneeId: "p-lin",
    reporterId: "p-xu",
    sprintId: null,
    versionId: "v-17",
    parentId: "it-101",
    storyPoints: 5,
    progress: 0,
    estimatedHours: null,
    tags: ["待办"],
    createdAt: "2026-09-26T04:00:00.000Z",
    updatedAt: "2026-09-28T09:00:00.000Z",
  }),
  item({
    id: "it-140",
    key: "HC-140",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "版本范围只展示挂在该版本上的事项",
    description: "冻结之后范围只读。退回测试才允许继续改范围。",
    priority: "MEDIUM",
    status: "APPROVED",
    assigneeId: "p-han",
    reporterId: "p-lin",
    sprintId: "sp-25",
    versionId: "v-18",
    parentId: "it-102",
    storyPoints: 5,
    progress: 0,
    estimatedHours: null,
    tags: ["版本"],
    createdAt: "2026-09-27T03:00:00.000Z",
    updatedAt: "2026-09-29T03:20:00.000Z",
  }),
  item({
    id: "it-118",
    key: "HC-118",
    projectId: "pr-hc",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "事项键在项目内连续且不可复用",
    description: "取消或拒绝不回收编号。新建事项取当前最大号加一。",
    priority: "LOW",
    status: "COMPLETED",
    assigneeId: "p-han",
    reporterId: "p-lin",
    sprintId: "sp-23",
    versionId: "v-16",
    parentId: "it-101",
    storyPoints: 2,
    progress: 100,
    estimatedHours: null,
    tags: ["事项"],
    createdAt: "2026-09-09T02:00:00.000Z",
    updatedAt: "2026-09-18T08:00:00.000Z",
  }),
  item({
    id: "it-141",
    key: "HC-141",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "开发任务",
    defectType: null,
    severity: null,
    title: "把任务状态机接到看板列",
    description: "待开始进待办，进行中和已暂停同列，完成进完成列。已取消默认不出现在看板上。",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assigneeId: "p-zhou",
    reporterId: "p-lin",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: 3,
    progress: 60,
    estimatedHours: 8,
    tags: ["看板"],
    createdAt: "2026-09-24T01:30:00.000Z",
    updatedAt: "2026-10-01T01:10:00.000Z",
  }),
  item({
    id: "it-142",
    key: "HC-142",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "开发任务",
    defectType: null,
    severity: null,
    title: "缺陷列映射补上待验证和测试中",
    description: "新建、已分配、重新打开留在待办。待验证和测试中进入验收列。",
    priority: "MEDIUM",
    status: "TODO",
    assigneeId: "p-han",
    reporterId: "p-zhou",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: 2,
    progress: 0,
    estimatedHours: 4,
    tags: ["缺陷"],
    createdAt: "2026-09-25T06:00:00.000Z",
    updatedAt: "2026-09-29T02:00:00.000Z",
  }),
  item({
    id: "it-144",
    key: "HC-144",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "文档任务",
    defectType: null,
    severity: null,
    title: "写看板空状态和非法流转提示",
    description: "列是空的时候说明这一列代表哪些状态。拖不动时列出当前允许的流转名称。",
    priority: "LOW",
    status: "PAUSED",
    assigneeId: "p-su",
    reporterId: "p-lin",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: 1,
    progress: 20,
    estimatedHours: 3,
    tags: ["文案"],
    createdAt: "2026-09-26T07:00:00.000Z",
    updatedAt: "2026-09-30T04:12:00.000Z",
  }),
  item({
    id: "it-150",
    key: "HC-150",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "测试任务",
    defectType: null,
    severity: null,
    title: "回归：草稿不能直接拖进开发中",
    description: "草稿只允许提交评审或取消。开始开发必须先批准。",
    priority: "HIGH",
    status: "TODO",
    assigneeId: "p-chen",
    reporterId: "p-zhou",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: 2,
    progress: 0,
    estimatedHours: 3,
    tags: ["测试"],
    createdAt: "2026-09-28T03:00:00.000Z",
    updatedAt: "2026-09-28T03:00:00.000Z",
  }),
  item({
    id: "it-151",
    key: "HC-151",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "开发任务",
    defectType: null,
    severity: null,
    title: "完成迭代时把未完成事项退回待办",
    description: "关闭进行中迭代前，选择把未完成事项移出迭代，而不是假装它们已经完成。",
    priority: "MEDIUM",
    status: "TODO",
    assigneeId: "p-lin",
    reporterId: "p-xu",
    sprintId: null,
    versionId: "v-17",
    parentId: "it-136",
    storyPoints: 3,
    progress: 0,
    estimatedHours: 5,
    tags: ["迭代"],
    createdAt: "2026-09-29T01:20:00.000Z",
    updatedAt: "2026-09-29T01:20:00.000Z",
  }),
  item({
    id: "it-90",
    key: "HC-90",
    projectId: "pr-hc",
    kind: "task",
    requirementType: null,
    taskType: "开发任务",
    defectType: null,
    severity: null,
    title: "项目内事项键生成",
    description: "已随 1.6 交付。",
    priority: "MEDIUM",
    status: "COMPLETED",
    assigneeId: "p-han",
    reporterId: "p-lin",
    sprintId: "sp-23",
    versionId: "v-16",
    parentId: "it-118",
    storyPoints: 2,
    progress: 100,
    estimatedHours: 4,
    tags: [],
    createdAt: "2026-09-10T02:00:00.000Z",
    updatedAt: "2026-09-16T09:00:00.000Z",
  }),
  item({
    id: "it-88",
    key: "HC-88",
    projectId: "pr-hc",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "功能缺陷",
    severity: "CRITICAL",
    title: "拖到完成列后刷新，状态又回到进行中",
    description: "看板本地改了列，刷新后仍读旧状态。完成必须写入生命周期历史，而不是只改卡片位置。",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assigneeId: "p-zhou",
    reporterId: "p-chen",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: null,
    progress: 30,
    estimatedHours: null,
    tags: ["看板"],
    createdAt: "2026-09-29T08:00:00.000Z",
    updatedAt: "2026-09-30T11:20:00.000Z",
  }),
  item({
    id: "it-91",
    key: "HC-91",
    projectId: "pr-hc",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "界面缺陷",
    severity: "MAJOR",
    title: "缺陷看板没有待验证列，验证人不知道该看哪",
    description: "待验证和测试中的缺陷挤在处理中，陈予安找不到该回归的单子。",
    priority: "HIGH",
    status: "PENDING_VERIFICATION",
    assigneeId: "p-chen",
    reporterId: "p-su",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: null,
    progress: 0,
    estimatedHours: null,
    tags: ["看板"],
    createdAt: "2026-09-27T05:40:00.000Z",
    updatedAt: "2026-09-30T07:05:00.000Z",
  }),
  item({
    id: "it-76",
    key: "HC-76",
    projectId: "pr-hc",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "功能缺陷",
    severity: "NORMAL",
    title: "已取消需求仍然出现在待办计数里",
    description: "取消不是删除。它不应该进入当前迭代的待办列，除非筛选打开「含已取消」。",
    priority: "MEDIUM",
    status: "RESOLVED",
    assigneeId: "p-han",
    reporterId: "p-lin",
    sprintId: "sp-23",
    versionId: "v-16",
    parentId: "it-136",
    storyPoints: null,
    progress: 100,
    estimatedHours: null,
    tags: ["筛选"],
    createdAt: "2026-09-14T02:00:00.000Z",
    updatedAt: "2026-09-18T04:00:00.000Z",
  }),
  item({
    id: "it-70",
    key: "HC-70",
    projectId: "pr-hc",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "功能缺陷",
    severity: "MAJOR",
    title: "评论被写进了领域审计",
    description: "讨论和事实流水被混成一条时间线。评论应只出现在评论页，对象动态不接受客户端补记。",
    priority: "HIGH",
    status: "CLOSED",
    assigneeId: "p-zhou",
    reporterId: "p-xu",
    sprintId: "sp-23",
    versionId: "v-16",
    parentId: "it-131",
    storyPoints: null,
    progress: 100,
    estimatedHours: null,
    tags: ["评论"],
    createdAt: "2026-09-11T02:00:00.000Z",
    updatedAt: "2026-09-17T06:30:00.000Z",
  }),
  item({
    id: "it-93",
    key: "HC-93",
    projectId: "pr-hc",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "界面缺陷",
    severity: "MINOR",
    title: "窄屏下看板把四列压成一列，卡片文字重叠",
    description: "手机宽度应横向滑动列，而不是把列宽压到无法阅读。",
    priority: "LOW",
    status: "NEW",
    assigneeId: null,
    reporterId: "p-su",
    sprintId: "sp-24",
    versionId: "v-17",
    parentId: "it-128",
    storyPoints: null,
    progress: 0,
    estimatedHours: null,
    tags: ["适配"],
    createdAt: "2026-09-30T09:00:00.000Z",
    updatedAt: "2026-09-30T09:00:00.000Z",
  }),
  item({
    id: "it-201",
    key: "PAY-18",
    projectId: "pr-pay",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "差异单可以指定负责人并提交验证",
    description: "对账差异超过阈值时生成事项，由开发处理、测试验证后关闭。",
    priority: "HIGH",
    status: "IN_DEVELOPMENT",
    assigneeId: "p-zhou",
    reporterId: "p-lin",
    sprintId: "sp-pay",
    versionId: "v-pay",
    parentId: null,
    storyPoints: 5,
    progress: 0,
    estimatedHours: null,
    tags: ["对账"],
    createdAt: "2026-09-28T02:00:00.000Z",
    updatedAt: "2026-09-30T02:00:00.000Z",
  }),
  item({
    id: "it-202",
    key: "PAY-19",
    projectId: "pr-pay",
    kind: "task",
    requirementType: null,
    taskType: "开发任务",
    defectType: null,
    severity: null,
    title: "导出差异时带上原订单号",
    description: "财务按订单号回查，只给内部编号他们没法对。",
    priority: "MEDIUM",
    status: "TODO",
    assigneeId: "p-zhou",
    reporterId: "p-lin",
    sprintId: "sp-pay",
    versionId: "v-pay",
    parentId: "it-201",
    storyPoints: 2,
    progress: 0,
    estimatedHours: 4,
    tags: [],
    createdAt: "2026-09-29T02:00:00.000Z",
    updatedAt: "2026-09-29T02:00:00.000Z",
  }),
  item({
    id: "it-203",
    key: "PAY-7",
    projectId: "pr-pay",
    kind: "defect",
    requirementType: null,
    taskType: null,
    defectType: "功能缺陷",
    severity: "MAJOR",
    title: "跨日切的回单被算成两笔差异",
    description: "23:50 到次日 00:10 的同一笔回单被日切切成两段。",
    priority: "HIGH",
    status: "ASSIGNED",
    assigneeId: "p-zhou",
    reporterId: "p-chen",
    sprintId: "sp-pay",
    versionId: "v-pay",
    parentId: null,
    storyPoints: null,
    progress: 0,
    estimatedHours: null,
    tags: ["日切"],
    createdAt: "2026-09-30T01:12:00.000Z",
    updatedAt: "2026-09-30T03:40:00.000Z",
  }),
  item({
    id: "it-301",
    key: "OPS-4",
    projectId: "pr-ops",
    kind: "requirement",
    requirementType: "Story",
    taskType: null,
    defectType: null,
    severity: null,
    title: "交接班只保留未关闭事项",
    description: "已完成和已关闭不进下一班的清单。",
    priority: "MEDIUM",
    status: "DRAFT",
    assigneeId: "p-han",
    reporterId: "p-han",
    sprintId: null,
    versionId: null,
    parentId: null,
    storyPoints: 3,
    progress: 0,
    estimatedHours: null,
    tags: ["值班"],
    createdAt: "2026-09-25T02:00:00.000Z",
    updatedAt: "2026-09-25T02:00:00.000Z",
  }),
];

export const comments: Comment[] = [
  {
    id: "c-1",
    itemId: "it-128",
    authorId: "p-chen",
    body: "草稿拖到进行中会被拒绝，这个我准备补一条回归。先别把提示写成“系统错误”。",
    createdAt: "2026-09-30T08:20:00.000Z",
  },
  {
    id: "c-2",
    itemId: "it-128",
    authorId: "p-zhou",
    body: "提示里我会带上流转名称，比如「提交评审」「取消」，不暴露状态码。",
    createdAt: "2026-09-30T09:05:00.000Z",
  },
  {
    id: "c-3",
    itemId: "it-131",
    authorId: "p-su",
    body: "评论框和对象动态不要共用一个输入。动态那边连编辑入口都不要留。",
    createdAt: "2026-09-30T06:10:00.000Z",
  },
  {
    id: "c-4",
    itemId: "it-88",
    authorId: "p-zhou",
    body: "复现了。拖拽只改了列顺序，没有写生命周期历史，刷新就回去了。",
    createdAt: "2026-09-30T11:00:00.000Z",
  },
  {
    id: "c-5",
    itemId: "it-91",
    authorId: "p-chen",
    body: "我按待验证来回归。通过就关，复现就重新打开。",
    createdAt: "2026-09-30T07:30:00.000Z",
  },
];

export const feeds: FeedEntry[] = [
  {
    id: "f-1",
    itemId: "it-128",
    projectId: "pr-hc",
    actorId: "p-lin",
    text: "把 HC-128 放进 Sprint 24，负责人改为周衡。",
    createdAt: "2026-09-24T02:00:00.000Z",
  },
  {
    id: "f-2",
    itemId: "it-128",
    projectId: "pr-hc",
    actorId: "p-zhou",
    text: "将状态从已批准流转为开发中。",
    createdAt: "2026-09-28T04:00:00.000Z",
  },
  {
    id: "f-3",
    itemId: "it-131",
    projectId: "pr-hc",
    actorId: "p-su",
    text: "将状态从草稿流转为评审中。",
    createdAt: "2026-09-29T06:00:00.000Z",
  },
  {
    id: "f-4",
    itemId: "it-88",
    projectId: "pr-hc",
    actorId: "p-chen",
    text: "创建了缺陷 HC-88。",
    createdAt: "2026-09-29T08:00:00.000Z",
  },
  {
    id: "f-5",
    itemId: "it-91",
    projectId: "pr-hc",
    actorId: "p-han",
    text: "将状态从处理中流转为待验证。",
    createdAt: "2026-09-30T07:05:00.000Z",
  },
  {
    id: "f-6",
    itemId: "it-141",
    projectId: "pr-hc",
    actorId: "p-zhou",
    text: "将状态从待开始流转为进行中。",
    createdAt: "2026-09-29T09:12:00.000Z",
  },
];

export const histories: LifecycleRecord[] = [
  {
    id: "h-1",
    itemId: "it-128",
    fromStatus: "DRAFT",
    toStatus: "REVIEW",
    transitionName: "提交评审",
    actorId: "p-lin",
    reason: null,
    createdAt: "2026-09-26T03:00:00.000Z",
  },
  {
    id: "h-2",
    itemId: "it-128",
    fromStatus: "REVIEW",
    toStatus: "APPROVED",
    transitionName: "批准",
    actorId: "p-xu",
    reason: null,
    createdAt: "2026-09-27T03:00:00.000Z",
  },
  {
    id: "h-3",
    itemId: "it-128",
    fromStatus: "APPROVED",
    toStatus: "IN_DEVELOPMENT",
    transitionName: "开始开发",
    actorId: "p-zhou",
    reason: null,
    createdAt: "2026-09-28T04:00:00.000Z",
  },
  {
    id: "h-4",
    itemId: "it-131",
    fromStatus: "DRAFT",
    toStatus: "REVIEW",
    transitionName: "提交评审",
    actorId: "p-su",
    reason: "详情信息架构需要评审",
    createdAt: "2026-09-29T06:00:00.000Z",
  },
  {
    id: "h-5",
    itemId: "it-91",
    fromStatus: "IN_PROGRESS",
    toStatus: "PENDING_VERIFICATION",
    transitionName: "提交验证",
    actorId: "p-han",
    reason: null,
    createdAt: "2026-09-30T07:05:00.000Z",
  },
  {
    id: "h-6",
    itemId: "it-141",
    fromStatus: "TODO",
    toStatus: "IN_PROGRESS",
    transitionName: "开始",
    actorId: "p-zhou",
    reason: null,
    createdAt: "2026-09-29T09:12:00.000Z",
  },
];

export const notices: Notice[] = [
  {
    id: "n-1",
    text: "陈予安在 HC-128 的评论里提到了流转提示",
    itemId: "it-128",
    read: false,
    createdAt: "2026-09-30T08:20:00.000Z",
  },
  {
    id: "n-2",
    text: "HC-91 待你验证",
    itemId: "it-91",
    read: false,
    createdAt: "2026-09-30T07:05:00.000Z",
  },
  {
    id: "n-3",
    text: "Sprint 24 将在 10 月 10 日结束",
    itemId: null,
    read: false,
    createdAt: "2026-09-30T01:00:00.000Z",
  },
  {
    id: "n-4",
    text: "HC-70 已关闭",
    itemId: "it-70",
    read: true,
    createdAt: "2026-09-17T06:30:00.000Z",
  },
];

const plan: Record<string, [string, string]> = {
  "it-141": ["2026-09-22", "2026-09-30"],
  "it-142": ["2026-09-28", "2026-10-08"],
  "it-144": ["2026-10-01", "2026-10-07"],
  "it-150": ["2026-09-22", "2026-09-26"],
  "it-128": ["2026-09-22", "2026-10-06"],
  "it-131": ["2026-09-24", "2026-10-03"],
  "it-101": ["2026-09-22", "2026-10-10"],
  "it-88": ["2026-09-29", "2026-10-09"],
  "it-91": ["2026-10-02", "2026-10-10"],
};
for (const entry of items) {
  const range = plan[entry.id];
  if (range) {
    entry.planStart = range[0];
    entry.planEnd = range[1];
  }
}

export const testCases: TestCase[] = [
  {
    id: "tc-12",
    key: "TC-12",
    projectId: "pr-hc",
    title: "只允许拖到当前状态可到达的列",
    testType: "功能测试",
    priority: "HIGH",
    status: "ACTIVE",
    suite: "看板回归",
    requirementId: "it-128",
    assigneeId: "p-chen",
    steps: [
      { action: "把草稿事项拖到进行中", expected: "不进入该列，并提示当前允许的流转" },
      { action: "把已批准事项拖到进行中", expected: "状态变为开发中" },
    ],
  },
  {
    id: "tc-18",
    key: "TC-18",
    projectId: "pr-hc",
    title: "非法拖拽给出可执行流转，而不是静默失败",
    testType: "功能测试",
    priority: "HIGH",
    status: "ACTIVE",
    suite: "看板回归",
    requirementId: "it-144",
    assigneeId: "p-chen",
    steps: [{ action: "把不允许的状态拖进完成列", expected: "提示可执行的流转，事项留在原列" }],
  },
  {
    id: "tc-21",
    key: "TC-21",
    projectId: "pr-hc",
    title: "评论只留在讨论，不写入对象动态",
    testType: "功能测试",
    priority: "MEDIUM",
    status: "REVIEW",
    suite: "事项详情",
    requirementId: "it-131",
    assigneeId: "p-su",
  },
  {
    id: "tc-7",
    key: "TC-7",
    projectId: "pr-hc",
    title: "版本冻结后不能再把事项加进范围",
    testType: "回归测试",
    priority: "MEDIUM",
    status: "DRAFT",
    suite: "发布门禁",
    requirementId: "it-102",
    assigneeId: "p-chen",
  },
  {
    id: "tc-3",
    key: "TC-3",
    projectId: "pr-pay",
    title: "差异单可以指派并进入验证",
    testType: "功能测试",
    priority: "HIGH",
    status: "ACTIVE",
    suite: "对账",
    requirementId: "it-201",
    assigneeId: "p-chen",
  },
];

export const testRuns: TestRun[] = [
  {
    id: "tr-17",
    projectId: "pr-hc",
    name: "1.7.0 回归",
    runType: "全量回归",
    status: "RUNNING",
    environment: "测试环境",
    versionId: "v-17",
    sourceRunId: null,
    cancelReason: null,
  },
  {
    id: "tr-16",
    projectId: "pr-hc",
    name: "1.6.0 回归",
    runType: "全量回归",
    status: "COMPLETED",
    environment: "测试环境",
    versionId: "v-16",
    sourceRunId: null,
    cancelReason: null,
  },
  {
    id: "tr-pay",
    projectId: "pr-pay",
    name: "对账抽测",
    runType: "定向复测",
    status: "CREATED",
    environment: "预发",
    versionId: "v-pay",
    sourceRunId: null,
    cancelReason: null,
  },
];

export const testExecutions: TestExecution[] = [
  { id: "ex-1", runId: "tr-17", caseId: "tc-12", result: "PASSED", defectId: null },
  { id: "ex-2", runId: "tr-17", caseId: "tc-18", result: "FAILED", defectId: null },
  { id: "ex-3", runId: "tr-17", caseId: "tc-21", result: null, defectId: null },
  { id: "ex-4", runId: "tr-17", caseId: "tc-7", result: "BLOCKED", defectId: null },
  { id: "ex-6", runId: "tr-16", caseId: "tc-12", result: "PASSED", defectId: null },
  { id: "ex-7", runId: "tr-16", caseId: "tc-18", result: "PASSED", defectId: null },
  { id: "ex-5", runId: "tr-pay", caseId: "tc-3", result: null, defectId: null },
];

export const workLogs: WorkLog[] = [
  { id: "wl-1", projectId: "pr-hc", itemId: "it-141", userId: "p-zhou", hours: 3.5, workDate: "2026-09-29", note: "把任务状态机接到看板列", status: "APPROVED" },
  { id: "wl-2", projectId: "pr-hc", itemId: "it-128", userId: "p-zhou", hours: 2, workDate: "2026-09-30", note: "补非法拖拽提示", status: "APPROVED" },
  { id: "wl-3", projectId: "pr-hc", itemId: "it-131", userId: "p-su", hours: 1.5, workDate: "2026-09-30", note: "拆开评论和对象动态", status: "PENDING" },
  { id: "wl-4", projectId: "pr-hc", itemId: "it-91", userId: "p-chen", hours: 2, workDate: "2026-10-01", note: "核对缺陷验证人", status: "PENDING" },
];

export const boards: Board[] = [
  { id: "bd-hc", projectId: "pr-hc", name: "主看板", sprintId: null },
  { id: "bd-hc-24", projectId: "pr-hc", name: "Sprint 24 看板", sprintId: "sp-24" },
  { id: "bd-pay", projectId: "pr-pay", name: "主看板", sprintId: null },
];

export const suites: TestSuite[] = [
  { id: "ts-board", projectId: "pr-hc", name: "看板回归" },
  { id: "ts-item", projectId: "pr-hc", name: "事项详情" },
  { id: "ts-gate", projectId: "pr-hc", name: "发布门禁" },
  { id: "ts-pay", projectId: "pr-pay", name: "对账" },
];

export const environments: ReleaseEnvironment[] = [
  { id: "env-test", projectId: "pr-hc", name: "测试环境", kind: "测试" },
  { id: "env-stage", projectId: "pr-hc", name: "预发", kind: "预发" },
  { id: "env-prod", projectId: "pr-hc", name: "生产", kind: "生产" },
  { id: "env-pay", projectId: "pr-pay", name: "预发", kind: "预发" },
];

export const releases: ReleaseRecord[] = [
  {
    id: "rel-17",
    projectId: "pr-hc",
    versionId: "v-17",
    environmentId: "env-test",
    title: "1.7.0 测试发布",
    summary: "看板拖拽和事项详情进入测试环境。",
    status: "DRAFT",
    createdAt: "2026-10-01T02:00:00.000Z",
  },
];

export const dependencies: TaskDependency[] = [
  {
    id: "dep-1",
    projectId: "pr-hc",
    predecessorId: "it-90",
    successorId: "it-141",
    dependencyType: "FS",
    lagDays: 0,
    memo: "事项键落地后才能改看板状态机",
    status: "ACTIVE",
  },
  {
    id: "dep-2",
    projectId: "pr-hc",
    predecessorId: "it-141",
    successorId: "it-142",
    dependencyType: "FS",
    lagDays: 0,
    memo: "状态机接上之后再补缺陷列",
    status: "ACTIVE",
  },
  {
    id: "dep-3",
    projectId: "pr-hc",
    predecessorId: "it-142",
    successorId: "it-150",
    dependencyType: "FS",
    lagDays: 1,
    memo: "列映射完成后再回归草稿拖拽",
    status: "ACTIVE",
  },
  {
    id: "dep-4",
    projectId: "pr-hc",
    predecessorId: "it-144",
    successorId: "it-151",
    dependencyType: "SS",
    lagDays: 0,
    memo: "文案和退回待办曾计划同时开始",
    status: "INACTIVE",
  },
];

export const seed = {
  people,
  projects,
  sprints,
  versions,
  items,
  comments,
  feeds,
  histories,
  notices,
  testCases,
  testRuns,
  testExecutions,
  workLogs,
  dependencies,
  boards,
  suites,
  environments,
  releases,
  currentUserId: "p-lin",
};
