/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PProjectKeyRouteImport } from './routes/p/$projectKey'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as PProjectKeyIndexRouteImport } from './routes/p/$projectKey/index'
import { Route as PProjectKeyAssignmentRouteImport } from './routes/p/$projectKey/assignment'
import { Route as PProjectKeyBacklogRouteImport } from './routes/p/$projectKey/backlog'
import { Route as PProjectKeyBoardsRouteImport } from './routes/p/$projectKey/boards'
import { Route as PProjectKeyDashboardRouteImport } from './routes/p/$projectKey/dashboard'
import { Route as PProjectKeyDefectsRouteImport } from './routes/p/$projectKey/defects'
import { Route as PProjectKeyDependenciesRouteImport } from './routes/p/$projectKey/dependencies'
import { Route as PProjectKeyGanttRouteImport } from './routes/p/$projectKey/gantt'
import { Route as PProjectKeyIssuesRouteImport } from './routes/p/$projectKey/issues'
import { Route as PProjectKeyReleaseEnvironmentsRouteImport } from './routes/p/$projectKey/release-environments'
import { Route as PProjectKeyReleasesRouteImport } from './routes/p/$projectKey/releases'
import { Route as PProjectKeyRequirementsRouteImport } from './routes/p/$projectKey/requirements'
import { Route as PProjectKeySettingsRouteImport } from './routes/p/$projectKey/settings'
import { Route as PProjectKeySprintsRouteImport } from './routes/p/$projectKey/sprints'
import { Route as PProjectKeyStatsRouteImport } from './routes/p/$projectKey/stats'
import { Route as PProjectKeyTestcasesRouteImport } from './routes/p/$projectKey/testcases'
import { Route as PProjectKeyTestsRouteImport } from './routes/p/$projectKey/tests'
import { Route as PProjectKeyTestsuitesRouteImport } from './routes/p/$projectKey/testsuites'
import { Route as PProjectKeyTraceRouteImport } from './routes/p/$projectKey/trace'
import { Route as PProjectKeyVersionsRouteImport } from './routes/p/$projectKey/versions'
import { Route as PProjectKeyTraceabilityRouteImport } from './routes/p/$projectKey/traceability'
import { Route as PProjectKeyWorklogsRouteImport } from './routes/p/$projectKey/worklogs'
import { Route as PProjectKeyDefectsIndexRouteImport } from './routes/p/$projectKey/defects/index'
import { Route as PProjectKeyDefectsDefectIdRouteImport } from './routes/p/$projectKey/defects/$defectId'
import { Route as PProjectKeyDefectsBoardRouteImport } from './routes/p/$projectKey/defects/board'
import { Route as PProjectKeyBoardsIndexRouteImport } from './routes/p/$projectKey/boards/index'
import { Route as PProjectKeyBoardsBoardIdRouteImport } from './routes/p/$projectKey/boards.$boardId'
import { Route as PProjectKeyIssuesIndexRouteImport } from './routes/p/$projectKey/issues/index'
import { Route as PProjectKeyIssuesTaskIdRouteImport } from './routes/p/$projectKey/issues/$taskId'
import { Route as PProjectKeyIssuesNewRouteImport } from './routes/p/$projectKey/issues/new'
import { Route as PProjectKeyItemsItemKeyRouteImport } from './routes/p/$projectKey/items/$itemKey'
import { Route as PProjectKeyReleaseEnvironmentsIndexRouteImport } from './routes/p/$projectKey/release-environments/index'
import { Route as PProjectKeyReleasesIndexRouteImport } from './routes/p/$projectKey/releases/index'
import { Route as PProjectKeyReleasesReleaseIdRouteImport } from './routes/p/$projectKey/releases/$releaseId'
import { Route as PProjectKeyRequirementsIndexRouteImport } from './routes/p/$projectKey/requirements/index'
import { Route as PProjectKeyRequirementsRequirementIdRouteImport } from './routes/p/$projectKey/requirements.$requirementId'
import { Route as PProjectKeyTestcasesIndexRouteImport } from './routes/p/$projectKey/testcases/index'
import { Route as PProjectKeyTestcasesTestCaseIdRouteImport } from './routes/p/$projectKey/testcases/$testCaseId'
import { Route as PProjectKeyTestsIndexRouteImport } from './routes/p/$projectKey/tests/index'
import { Route as PProjectKeyTestsTestRunIdRouteImport } from './routes/p/$projectKey/tests/$testRunId'
import { Route as PProjectKeyTestsuitesIndexRouteImport } from './routes/p/$projectKey/testsuites/index'
import { Route as PProjectKeyTestsuitesTestSuiteIdRouteImport } from './routes/p/$projectKey/testsuites/$testSuiteId'
import { Route as PProjectKeyVersionsIndexRouteImport } from './routes/p/$projectKey/versions/index'
import { Route as PProjectKeyVersionsVersionIdRouteImport } from './routes/p/$projectKey/versions/$versionId'
import { Route as PProjectKeySprintsIndexRouteImport } from './routes/p/$projectKey/sprints/index'
import { Route as PProjectKeySprintsSprintIdRouteImport } from './routes/p/$projectKey/sprints/$sprintId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectKeyRoute = PProjectKeyRouteImport.update({
  id: '/p/$projectKey',
  path: '/p/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectKeyIndexRoute = PProjectKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyAssignmentRoute = PProjectKeyAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyBacklogRoute = PProjectKeyBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyBoardsRoute = PProjectKeyBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDashboardRoute = PProjectKeyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDefectsRoute = PProjectKeyDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDependenciesRoute = PProjectKeyDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyGanttRoute = PProjectKeyGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyIssuesRoute = PProjectKeyIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyReleaseEnvironmentsRoute =
  PProjectKeyReleaseEnvironmentsRouteImport.update({
    id: '/release-environments',
    path: '/release-environments',
    getParentRoute: () => PProjectKeyRoute,
  } as any)
const PProjectKeyReleasesRoute = PProjectKeyReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyRequirementsRoute = PProjectKeyRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeySettingsRoute = PProjectKeySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeySprintsRoute = PProjectKeySprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyStatsRoute = PProjectKeyStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTestcasesRoute = PProjectKeyTestcasesRouteImport.update({
  id: '/testcases',
  path: '/testcases',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTestsRoute = PProjectKeyTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTestsuitesRoute = PProjectKeyTestsuitesRouteImport.update({
  id: '/testsuites',
  path: '/testsuites',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTraceRoute = PProjectKeyTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyVersionsRoute = PProjectKeyVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
const PProjectKeyTraceabilityRoute = PProjectKeyTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyWorklogsRoute = PProjectKeyWorklogsRouteImport.update({
  id: '/worklogs',
  path: '/worklogs',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDefectsIndexRoute = PProjectKeyDefectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyDefectsRoute,
} as any)
const PProjectKeyDefectsDefectIdRoute =
  PProjectKeyDefectsDefectIdRouteImport.update({
    id: '/$defectId',
    path: '/$defectId',
    getParentRoute: () => PProjectKeyDefectsRoute,
  } as any)
const PProjectKeyDefectsBoardRoute = PProjectKeyDefectsBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => PProjectKeyDefectsRoute,
const PProjectKeyBoardsIndexRoute = PProjectKeyBoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyBoardsRoute,
} as any)
const PProjectKeyBoardsBoardIdRoute =
  PProjectKeyBoardsBoardIdRouteImport.update({
    id: '/$boardId',
    path: '/$boardId',
    getParentRoute: () => PProjectKeyBoardsRoute,
  } as any)
const PProjectKeyIssuesIndexRoute = PProjectKeyIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyIssuesRoute,
} as any)
const PProjectKeyIssuesTaskIdRoute = PProjectKeyIssuesTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => PProjectKeyIssuesRoute,
} as any)
const PProjectKeyIssuesNewRoute = PProjectKeyIssuesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PProjectKeyIssuesRoute,
} as any)
const PProjectKeyItemsItemKeyRoute = PProjectKeyItemsItemKeyRouteImport.update({
  id: '/items/$itemKey',
  path: '/items/$itemKey',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyReleaseEnvironmentsIndexRoute =
  PProjectKeyReleaseEnvironmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyReleaseEnvironmentsRoute,
  } as any)
const PProjectKeyReleasesIndexRoute =
  PProjectKeyReleasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyReleasesRoute,
  } as any)
const PProjectKeyReleasesReleaseIdRoute =
  PProjectKeyReleasesReleaseIdRouteImport.update({
    id: '/$releaseId',
    path: '/$releaseId',
    getParentRoute: () => PProjectKeyReleasesRoute,
  } as any)
const PProjectKeyRequirementsIndexRoute =
  PProjectKeyRequirementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyRequirementsRoute,
  } as any)
const PProjectKeyRequirementsRequirementIdRoute =
  PProjectKeyRequirementsRequirementIdRouteImport.update({
    id: '/$requirementId',
    path: '/$requirementId',
    getParentRoute: () => PProjectKeyRequirementsRoute,
  } as any)
const PProjectKeyTestcasesIndexRoute =
  PProjectKeyTestcasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyTestcasesRoute,
  } as any)
const PProjectKeyTestcasesTestCaseIdRoute =
  PProjectKeyTestcasesTestCaseIdRouteImport.update({
    id: '/$testCaseId',
    path: '/$testCaseId',
    getParentRoute: () => PProjectKeyTestcasesRoute,
  } as any)
const PProjectKeyTestsIndexRoute = PProjectKeyTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyTestsRoute,
} as any)
const PProjectKeyTestsTestRunIdRoute =
  PProjectKeyTestsTestRunIdRouteImport.update({
    id: '/$testRunId',
    path: '/$testRunId',
    getParentRoute: () => PProjectKeyTestsRoute,
  } as any)
const PProjectKeyTestsuitesIndexRoute =
  PProjectKeyTestsuitesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyTestsuitesRoute,
  } as any)
const PProjectKeyTestsuitesTestSuiteIdRoute =
  PProjectKeyTestsuitesTestSuiteIdRouteImport.update({
    id: '/$testSuiteId',
    path: '/$testSuiteId',
    getParentRoute: () => PProjectKeyTestsuitesRoute,
  } as any)
const PProjectKeyVersionsIndexRoute =
  PProjectKeyVersionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectKeyVersionsRoute,
  } as any)
const PProjectKeyVersionsVersionIdRoute =
  PProjectKeyVersionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => PProjectKeyVersionsRoute,
const PProjectKeySprintsIndexRoute = PProjectKeySprintsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeySprintsRoute,
} as any)
const PProjectKeySprintsSprintIdRoute =
  PProjectKeySprintsSprintIdRouteImport.update({
    id: '/$sprintId',
    path: '/$sprintId',
    getParentRoute: () => PProjectKeySprintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/p/$projectKey': typeof PProjectKeyRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/p/$projectKey/assignment': typeof PProjectKeyAssignmentRoute
  '/p/$projectKey/backlog': typeof PProjectKeyBacklogRoute
  '/p/$projectKey/boards': typeof PProjectKeyBoardsRouteWithChildren
  '/p/$projectKey/dashboard': typeof PProjectKeyDashboardRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsRouteWithChildren
  '/p/$projectKey/dependencies': typeof PProjectKeyDependenciesRoute
  '/p/$projectKey/gantt': typeof PProjectKeyGanttRoute
  '/p/$projectKey/issues': typeof PProjectKeyIssuesRouteWithChildren
  '/p/$projectKey/release-environments': typeof PProjectKeyReleaseEnvironmentsRouteWithChildren
  '/p/$projectKey/releases': typeof PProjectKeyReleasesRouteWithChildren
  '/p/$projectKey/requirements': typeof PProjectKeyRequirementsRouteWithChildren
  '/p/$projectKey/settings': typeof PProjectKeySettingsRoute
  '/p/$projectKey/sprints': typeof PProjectKeySprintsRouteWithChildren
  '/p/$projectKey/stats': typeof PProjectKeyStatsRoute
  '/p/$projectKey/testcases': typeof PProjectKeyTestcasesRouteWithChildren
  '/p/$projectKey/tests': typeof PProjectKeyTestsRouteWithChildren
  '/p/$projectKey/testsuites': typeof PProjectKeyTestsuitesRouteWithChildren
  '/p/$projectKey/trace': typeof PProjectKeyTraceRoute
  '/p/$projectKey/versions': typeof PProjectKeyVersionsRouteWithChildren
  '/p/$projectKey/traceability': typeof PProjectKeyTraceabilityRoute
  '/p/$projectKey/worklogs': typeof PProjectKeyWorklogsRoute
  '/p/$projectKey/': typeof PProjectKeyIndexRoute
  '/p/$projectKey/defects/$defectId': typeof PProjectKeyDefectsDefectIdRoute
  '/p/$projectKey/defects/board': typeof PProjectKeyDefectsBoardRoute
  '/p/$projectKey/boards/$boardId': typeof PProjectKeyBoardsBoardIdRoute
  '/p/$projectKey/issues/$taskId': typeof PProjectKeyIssuesTaskIdRoute
  '/p/$projectKey/issues/new': typeof PProjectKeyIssuesNewRoute
  '/p/$projectKey/items/$itemKey': typeof PProjectKeyItemsItemKeyRoute
  '/p/$projectKey/releases/$releaseId': typeof PProjectKeyReleasesReleaseIdRoute
  '/p/$projectKey/requirements/$requirementId': typeof PProjectKeyRequirementsRequirementIdRoute
  '/p/$projectKey/testcases/$testCaseId': typeof PProjectKeyTestcasesTestCaseIdRoute
  '/p/$projectKey/tests/$testRunId': typeof PProjectKeyTestsTestRunIdRoute
  '/p/$projectKey/testsuites/$testSuiteId': typeof PProjectKeyTestsuitesTestSuiteIdRoute
  '/p/$projectKey/versions/$versionId': typeof PProjectKeyVersionsVersionIdRoute
  '/p/$projectKey/defects/': typeof PProjectKeyDefectsIndexRoute
  '/p/$projectKey/sprints/$sprintId': typeof PProjectKeySprintsSprintIdRoute
  '/p/$projectKey/boards/': typeof PProjectKeyBoardsIndexRoute
  '/p/$projectKey/issues/': typeof PProjectKeyIssuesIndexRoute
  '/p/$projectKey/release-environments/': typeof PProjectKeyReleaseEnvironmentsIndexRoute
  '/p/$projectKey/releases/': typeof PProjectKeyReleasesIndexRoute
  '/p/$projectKey/requirements/': typeof PProjectKeyRequirementsIndexRoute
  '/p/$projectKey/testcases/': typeof PProjectKeyTestcasesIndexRoute
  '/p/$projectKey/tests/': typeof PProjectKeyTestsIndexRoute
  '/p/$projectKey/testsuites/': typeof PProjectKeyTestsuitesIndexRoute
  '/p/$projectKey/versions/': typeof PProjectKeyVersionsIndexRoute
  '/p/$projectKey/sprints/': typeof PProjectKeySprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/projects/new': typeof ProjectsNewRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsRoute
  '/p/$projectKey/releases': typeof PProjectKeyReleasesRoute
  '/p/$projectKey/tests': typeof PProjectKeyTestsRoute
  '/p/$projectKey': typeof PProjectKeyIndexRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsIndexRoute
  '/p/$projectKey/boards': typeof PProjectKeyBoardsIndexRoute
  '/p/$projectKey/issues': typeof PProjectKeyIssuesIndexRoute
  '/p/$projectKey/release-environments': typeof PProjectKeyReleaseEnvironmentsIndexRoute
  '/p/$projectKey/releases': typeof PProjectKeyReleasesIndexRoute
  '/p/$projectKey/requirements': typeof PProjectKeyRequirementsIndexRoute
  '/p/$projectKey/testcases': typeof PProjectKeyTestcasesIndexRoute
  '/p/$projectKey/tests': typeof PProjectKeyTestsIndexRoute
  '/p/$projectKey/testsuites': typeof PProjectKeyTestsuitesIndexRoute
  '/p/$projectKey/versions': typeof PProjectKeyVersionsIndexRoute
  '/p/$projectKey/sprints': typeof PProjectKeySprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/projects_/new': typeof ProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/login'
    | '/me'
    | '/projects'
    | '/p/$projectKey'
    | '/projects/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/boards'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/release-environments'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/sprints'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/testcases'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/testsuites'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/versions'
    | '/p/$projectKey/traceability'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey/'
    | '/p/$projectKey/defects/$defectId'
    | '/p/$projectKey/defects/board'
    | '/p/$projectKey/boards/$boardId'
    | '/p/$projectKey/issues/$taskId'
    | '/p/$projectKey/issues/new'
    | '/p/$projectKey/items/$itemKey'
    | '/p/$projectKey/releases/$releaseId'
    | '/p/$projectKey/requirements/$requirementId'
    | '/p/$projectKey/testcases/$testCaseId'
    | '/p/$projectKey/tests/$testRunId'
    | '/p/$projectKey/testsuites/$testSuiteId'
    | '/p/$projectKey/versions/$versionId'
    | '/p/$projectKey/defects/'
    | '/p/$projectKey/sprints/$sprintId'
    | '/p/$projectKey/boards/'
    | '/p/$projectKey/issues/'
    | '/p/$projectKey/release-environments/'
    | '/p/$projectKey/releases/'
    | '/p/$projectKey/requirements/'
    | '/p/$projectKey/testcases/'
    | '/p/$projectKey/tests/'
    | '/p/$projectKey/testsuites/'
    | '/p/$projectKey/versions/'
    | '/p/$projectKey/sprints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/login'
    | '/me'
    | '/projects'
    | '/projects/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/traceability'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey'
    | '/p/$projectKey/defects/$defectId'
    | '/p/$projectKey/defects/board'
    | '/p/$projectKey/boards/$boardId'
    | '/p/$projectKey/issues/$taskId'
    | '/p/$projectKey/issues/new'
    | '/p/$projectKey/items/$itemKey'
    | '/p/$projectKey/releases/$releaseId'
    | '/p/$projectKey/requirements/$requirementId'
    | '/p/$projectKey/testcases/$testCaseId'
    | '/p/$projectKey/tests/$testRunId'
    | '/p/$projectKey/testsuites/$testSuiteId'
    | '/p/$projectKey/versions/$versionId'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/sprints/$sprintId'
    | '/p/$projectKey/boards'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/release-environments'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/testcases'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/testsuites'
    | '/p/$projectKey/versions'
    | '/p/$projectKey/sprints'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/login'
    | '/me'
    | '/projects'
    | '/p/$projectKey'
    | '/projects_/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/boards'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/release-environments'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/sprints'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/testcases'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/testsuites'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/versions'
    | '/p/$projectKey/traceability'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey/'
    | '/p/$projectKey/defects/$defectId'
    | '/p/$projectKey/defects/board'
    | '/p/$projectKey/boards/$boardId'
    | '/p/$projectKey/issues/$taskId'
    | '/p/$projectKey/issues/new'
    | '/p/$projectKey/items/$itemKey'
    | '/p/$projectKey/releases/$releaseId'
    | '/p/$projectKey/requirements/$requirementId'
    | '/p/$projectKey/testcases/$testCaseId'
    | '/p/$projectKey/tests/$testRunId'
    | '/p/$projectKey/testsuites/$testSuiteId'
    | '/p/$projectKey/versions/$versionId'
    | '/p/$projectKey/defects/'
    | '/p/$projectKey/sprints/$sprintId'
    | '/p/$projectKey/boards/'
    | '/p/$projectKey/issues/'
    | '/p/$projectKey/release-environments/'
    | '/p/$projectKey/releases/'
    | '/p/$projectKey/requirements/'
    | '/p/$projectKey/testcases/'
    | '/p/$projectKey/tests/'
    | '/p/$projectKey/testsuites/'
    | '/p/$projectKey/versions/'
    | '/p/$projectKey/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  ProjectsRoute: typeof ProjectsRoute
  PProjectKeyRoute: typeof PProjectKeyRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectKey': {
      id: '/p/$projectKey'
      path: '/p/$projectKey'
      fullPath: '/p/$projectKey'
      preLoaderRoute: typeof PProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectKey/': {
      id: '/p/$projectKey/'
      path: '/'
      fullPath: '/p/$projectKey/'
      preLoaderRoute: typeof PProjectKeyIndexRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/assignment': {
      id: '/p/$projectKey/assignment'
      path: '/assignment'
      fullPath: '/p/$projectKey/assignment'
      preLoaderRoute: typeof PProjectKeyAssignmentRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/backlog': {
      id: '/p/$projectKey/backlog'
      path: '/backlog'
      fullPath: '/p/$projectKey/backlog'
      preLoaderRoute: typeof PProjectKeyBacklogRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/boards': {
      id: '/p/$projectKey/boards'
      path: '/boards'
      fullPath: '/p/$projectKey/boards'
      preLoaderRoute: typeof PProjectKeyBoardsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/dashboard': {
      id: '/p/$projectKey/dashboard'
      path: '/dashboard'
      fullPath: '/p/$projectKey/dashboard'
      preLoaderRoute: typeof PProjectKeyDashboardRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/defects': {
      id: '/p/$projectKey/defects'
      path: '/defects'
      fullPath: '/p/$projectKey/defects'
      preLoaderRoute: typeof PProjectKeyDefectsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/dependencies': {
      id: '/p/$projectKey/dependencies'
      path: '/dependencies'
      fullPath: '/p/$projectKey/dependencies'
      preLoaderRoute: typeof PProjectKeyDependenciesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/gantt': {
      id: '/p/$projectKey/gantt'
      path: '/gantt'
      fullPath: '/p/$projectKey/gantt'
      preLoaderRoute: typeof PProjectKeyGanttRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/issues': {
      id: '/p/$projectKey/issues'
      path: '/issues'
      fullPath: '/p/$projectKey/issues'
      preLoaderRoute: typeof PProjectKeyIssuesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/release-environments': {
      id: '/p/$projectKey/release-environments'
      path: '/release-environments'
      fullPath: '/p/$projectKey/release-environments'
      preLoaderRoute: typeof PProjectKeyReleaseEnvironmentsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/releases': {
      id: '/p/$projectKey/releases'
      path: '/releases'
      fullPath: '/p/$projectKey/releases'
      preLoaderRoute: typeof PProjectKeyReleasesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/requirements': {
      id: '/p/$projectKey/requirements'
      path: '/requirements'
      fullPath: '/p/$projectKey/requirements'
      preLoaderRoute: typeof PProjectKeyRequirementsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/settings': {
      id: '/p/$projectKey/settings'
      path: '/settings'
      fullPath: '/p/$projectKey/settings'
      preLoaderRoute: typeof PProjectKeySettingsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/sprints': {
      id: '/p/$projectKey/sprints'
      path: '/sprints'
      fullPath: '/p/$projectKey/sprints'
      preLoaderRoute: typeof PProjectKeySprintsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/stats': {
      id: '/p/$projectKey/stats'
      path: '/stats'
      fullPath: '/p/$projectKey/stats'
      preLoaderRoute: typeof PProjectKeyStatsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/testcases': {
      id: '/p/$projectKey/testcases'
      path: '/testcases'
      fullPath: '/p/$projectKey/testcases'
      preLoaderRoute: typeof PProjectKeyTestcasesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/tests': {
      id: '/p/$projectKey/tests'
      path: '/tests'
      fullPath: '/p/$projectKey/tests'
      preLoaderRoute: typeof PProjectKeyTestsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/testsuites': {
      id: '/p/$projectKey/testsuites'
      path: '/testsuites'
      fullPath: '/p/$projectKey/testsuites'
      preLoaderRoute: typeof PProjectKeyTestsuitesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/trace': {
      id: '/p/$projectKey/trace'
      path: '/trace'
      fullPath: '/p/$projectKey/trace'
      preLoaderRoute: typeof PProjectKeyTraceRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/versions': {
      id: '/p/$projectKey/versions'
      path: '/versions'
      fullPath: '/p/$projectKey/versions'
      preLoaderRoute: typeof PProjectKeyVersionsRouteImport
    '/p/$projectKey/traceability': {
      id: '/p/$projectKey/traceability'
      path: '/traceability'
      fullPath: '/p/$projectKey/traceability'
      preLoaderRoute: typeof PProjectKeyTraceabilityRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/worklogs': {
      id: '/p/$projectKey/worklogs'
      path: '/worklogs'
      fullPath: '/p/$projectKey/worklogs'
      preLoaderRoute: typeof PProjectKeyWorklogsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/defects/': {
      id: '/p/$projectKey/defects/'
      path: '/'
      fullPath: '/p/$projectKey/defects/'
      preLoaderRoute: typeof PProjectKeyDefectsIndexRouteImport
      parentRoute: typeof PProjectKeyDefectsRoute
    }
    '/p/$projectKey/defects/$defectId': {
      id: '/p/$projectKey/defects/$defectId'
      path: '/$defectId'
      fullPath: '/p/$projectKey/defects/$defectId'
      preLoaderRoute: typeof PProjectKeyDefectsDefectIdRouteImport
      parentRoute: typeof PProjectKeyDefectsRoute
    }
    '/p/$projectKey/defects/board': {
      id: '/p/$projectKey/defects/board'
      path: '/board'
      fullPath: '/p/$projectKey/defects/board'
      preLoaderRoute: typeof PProjectKeyDefectsBoardRouteImport
      parentRoute: typeof PProjectKeyDefectsRoute
    '/p/$projectKey/boards/': {
      id: '/p/$projectKey/boards/'
      path: '/'
      fullPath: '/p/$projectKey/boards/'
      preLoaderRoute: typeof PProjectKeyBoardsIndexRouteImport
      parentRoute: typeof PProjectKeyBoardsRoute
    }
    '/p/$projectKey/boards/$boardId': {
      id: '/p/$projectKey/boards/$boardId'
      path: '/$boardId'
      fullPath: '/p/$projectKey/boards/$boardId'
      preLoaderRoute: typeof PProjectKeyBoardsBoardIdRouteImport
      parentRoute: typeof PProjectKeyBoardsRoute
    }
    '/p/$projectKey/issues/': {
      id: '/p/$projectKey/issues/'
      path: '/'
      fullPath: '/p/$projectKey/issues/'
      preLoaderRoute: typeof PProjectKeyIssuesIndexRouteImport
      parentRoute: typeof PProjectKeyIssuesRoute
    }
    '/p/$projectKey/issues/$taskId': {
      id: '/p/$projectKey/issues/$taskId'
      path: '/$taskId'
      fullPath: '/p/$projectKey/issues/$taskId'
      preLoaderRoute: typeof PProjectKeyIssuesTaskIdRouteImport
      parentRoute: typeof PProjectKeyIssuesRoute
    }
    '/p/$projectKey/issues/new': {
      id: '/p/$projectKey/issues/new'
      path: '/new'
      fullPath: '/p/$projectKey/issues/new'
      preLoaderRoute: typeof PProjectKeyIssuesNewRouteImport
      parentRoute: typeof PProjectKeyIssuesRoute
    }
    '/p/$projectKey/items/$itemKey': {
      id: '/p/$projectKey/items/$itemKey'
      path: '/items/$itemKey'
      fullPath: '/p/$projectKey/items/$itemKey'
      preLoaderRoute: typeof PProjectKeyItemsItemKeyRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/release-environments/': {
      id: '/p/$projectKey/release-environments/'
      path: '/'
      fullPath: '/p/$projectKey/release-environments/'
      preLoaderRoute: typeof PProjectKeyReleaseEnvironmentsIndexRouteImport
      parentRoute: typeof PProjectKeyReleaseEnvironmentsRoute
    }
    '/p/$projectKey/releases/': {
      id: '/p/$projectKey/releases/'
      path: '/'
      fullPath: '/p/$projectKey/releases/'
      preLoaderRoute: typeof PProjectKeyReleasesIndexRouteImport
      parentRoute: typeof PProjectKeyReleasesRoute
    }
    '/p/$projectKey/releases/$releaseId': {
      id: '/p/$projectKey/releases/$releaseId'
      path: '/$releaseId'
      fullPath: '/p/$projectKey/releases/$releaseId'
      preLoaderRoute: typeof PProjectKeyReleasesReleaseIdRouteImport
      parentRoute: typeof PProjectKeyReleasesRoute
    }
    '/p/$projectKey/requirements/': {
      id: '/p/$projectKey/requirements/'
      path: '/'
      fullPath: '/p/$projectKey/requirements/'
      preLoaderRoute: typeof PProjectKeyRequirementsIndexRouteImport
      parentRoute: typeof PProjectKeyRequirementsRoute
    }
    '/p/$projectKey/requirements/$requirementId': {
      id: '/p/$projectKey/requirements/$requirementId'
      path: '/$requirementId'
      fullPath: '/p/$projectKey/requirements/$requirementId'
      preLoaderRoute: typeof PProjectKeyRequirementsRequirementIdRouteImport
      parentRoute: typeof PProjectKeyRequirementsRoute
    }
    '/p/$projectKey/testcases/': {
      id: '/p/$projectKey/testcases/'
      path: '/'
      fullPath: '/p/$projectKey/testcases/'
      preLoaderRoute: typeof PProjectKeyTestcasesIndexRouteImport
      parentRoute: typeof PProjectKeyTestcasesRoute
    }
    '/p/$projectKey/testcases/$testCaseId': {
      id: '/p/$projectKey/testcases/$testCaseId'
      path: '/$testCaseId'
      fullPath: '/p/$projectKey/testcases/$testCaseId'
      preLoaderRoute: typeof PProjectKeyTestcasesTestCaseIdRouteImport
      parentRoute: typeof PProjectKeyTestcasesRoute
    }
    '/p/$projectKey/tests/': {
      id: '/p/$projectKey/tests/'
      path: '/'
      fullPath: '/p/$projectKey/tests/'
      preLoaderRoute: typeof PProjectKeyTestsIndexRouteImport
      parentRoute: typeof PProjectKeyTestsRoute
    }
    '/p/$projectKey/tests/$testRunId': {
      id: '/p/$projectKey/tests/$testRunId'
      path: '/$testRunId'
      fullPath: '/p/$projectKey/tests/$testRunId'
      preLoaderRoute: typeof PProjectKeyTestsTestRunIdRouteImport
      parentRoute: typeof PProjectKeyTestsRoute
    }
    '/p/$projectKey/testsuites/': {
      id: '/p/$projectKey/testsuites/'
      path: '/'
      fullPath: '/p/$projectKey/testsuites/'
      preLoaderRoute: typeof PProjectKeyTestsuitesIndexRouteImport
      parentRoute: typeof PProjectKeyTestsuitesRoute
    }
    '/p/$projectKey/testsuites/$testSuiteId': {
      id: '/p/$projectKey/testsuites/$testSuiteId'
      path: '/$testSuiteId'
      fullPath: '/p/$projectKey/testsuites/$testSuiteId'
      preLoaderRoute: typeof PProjectKeyTestsuitesTestSuiteIdRouteImport
      parentRoute: typeof PProjectKeyTestsuitesRoute
    }
    '/p/$projectKey/versions/': {
      id: '/p/$projectKey/versions/'
      path: '/'
      fullPath: '/p/$projectKey/versions/'
      preLoaderRoute: typeof PProjectKeyVersionsIndexRouteImport
      parentRoute: typeof PProjectKeyVersionsRoute
    }
    '/p/$projectKey/versions/$versionId': {
      id: '/p/$projectKey/versions/$versionId'
      path: '/$versionId'
      fullPath: '/p/$projectKey/versions/$versionId'
      preLoaderRoute: typeof PProjectKeyVersionsVersionIdRouteImport
      parentRoute: typeof PProjectKeyVersionsRoute
    '/p/$projectKey/sprints/': {
      id: '/p/$projectKey/sprints/'
      path: '/'
      fullPath: '/p/$projectKey/sprints/'
      preLoaderRoute: typeof PProjectKeySprintsIndexRouteImport
      parentRoute: typeof PProjectKeySprintsRoute
    }
    '/p/$projectKey/sprints/$sprintId': {
      id: '/p/$projectKey/sprints/$sprintId'
      path: '/$sprintId'
      fullPath: '/p/$projectKey/sprints/$sprintId'
      preLoaderRoute: typeof PProjectKeySprintsSprintIdRouteImport
      parentRoute: typeof PProjectKeySprintsRoute
    }
  }
}

interface PProjectKeyDefectsRouteChildren {
  PProjectKeyDefectsDefectIdRoute: typeof PProjectKeyDefectsDefectIdRoute
  PProjectKeyDefectsBoardRoute: typeof PProjectKeyDefectsBoardRoute
  PProjectKeyDefectsIndexRoute: typeof PProjectKeyDefectsIndexRoute
}

const PProjectKeyDefectsRouteChildren: PProjectKeyDefectsRouteChildren = {
  PProjectKeyDefectsDefectIdRoute: PProjectKeyDefectsDefectIdRoute,
  PProjectKeyDefectsBoardRoute: PProjectKeyDefectsBoardRoute,
  PProjectKeyDefectsIndexRoute: PProjectKeyDefectsIndexRoute,
}

const PProjectKeyDefectsRouteWithChildren =
  PProjectKeyDefectsRoute._addFileChildren(PProjectKeyDefectsRouteChildren)
interface PProjectKeyBoardsRouteChildren {
  PProjectKeyBoardsBoardIdRoute: typeof PProjectKeyBoardsBoardIdRoute
  PProjectKeyBoardsIndexRoute: typeof PProjectKeyBoardsIndexRoute
}

const PProjectKeyBoardsRouteChildren: PProjectKeyBoardsRouteChildren = {
  PProjectKeyBoardsBoardIdRoute: PProjectKeyBoardsBoardIdRoute,
  PProjectKeyBoardsIndexRoute: PProjectKeyBoardsIndexRoute,
}

const PProjectKeyBoardsRouteWithChildren =
  PProjectKeyBoardsRoute._addFileChildren(PProjectKeyBoardsRouteChildren)

interface PProjectKeyIssuesRouteChildren {
  PProjectKeyIssuesTaskIdRoute: typeof PProjectKeyIssuesTaskIdRoute
  PProjectKeyIssuesNewRoute: typeof PProjectKeyIssuesNewRoute
  PProjectKeyIssuesIndexRoute: typeof PProjectKeyIssuesIndexRoute
}

const PProjectKeyIssuesRouteChildren: PProjectKeyIssuesRouteChildren = {
  PProjectKeyIssuesTaskIdRoute: PProjectKeyIssuesTaskIdRoute,
  PProjectKeyIssuesNewRoute: PProjectKeyIssuesNewRoute,
  PProjectKeyIssuesIndexRoute: PProjectKeyIssuesIndexRoute,
}

const PProjectKeyIssuesRouteWithChildren =
  PProjectKeyIssuesRoute._addFileChildren(PProjectKeyIssuesRouteChildren)

interface PProjectKeyReleaseEnvironmentsRouteChildren {
  PProjectKeyReleaseEnvironmentsIndexRoute: typeof PProjectKeyReleaseEnvironmentsIndexRoute
}

const PProjectKeyReleaseEnvironmentsRouteChildren: PProjectKeyReleaseEnvironmentsRouteChildren =
  {
    PProjectKeyReleaseEnvironmentsIndexRoute:
      PProjectKeyReleaseEnvironmentsIndexRoute,
  }

const PProjectKeyReleaseEnvironmentsRouteWithChildren =
  PProjectKeyReleaseEnvironmentsRoute._addFileChildren(
    PProjectKeyReleaseEnvironmentsRouteChildren,
  )

interface PProjectKeyReleasesRouteChildren {
  PProjectKeyReleasesReleaseIdRoute: typeof PProjectKeyReleasesReleaseIdRoute
  PProjectKeyReleasesIndexRoute: typeof PProjectKeyReleasesIndexRoute
}

const PProjectKeyReleasesRouteChildren: PProjectKeyReleasesRouteChildren = {
  PProjectKeyReleasesReleaseIdRoute: PProjectKeyReleasesReleaseIdRoute,
  PProjectKeyReleasesIndexRoute: PProjectKeyReleasesIndexRoute,
}

const PProjectKeyReleasesRouteWithChildren =
  PProjectKeyReleasesRoute._addFileChildren(PProjectKeyReleasesRouteChildren)

interface PProjectKeyRequirementsRouteChildren {
  PProjectKeyRequirementsRequirementIdRoute: typeof PProjectKeyRequirementsRequirementIdRoute
  PProjectKeyRequirementsIndexRoute: typeof PProjectKeyRequirementsIndexRoute
}

const PProjectKeyRequirementsRouteChildren: PProjectKeyRequirementsRouteChildren =
  {
    PProjectKeyRequirementsRequirementIdRoute:
      PProjectKeyRequirementsRequirementIdRoute,
    PProjectKeyRequirementsIndexRoute: PProjectKeyRequirementsIndexRoute,
  }

const PProjectKeyRequirementsRouteWithChildren =
  PProjectKeyRequirementsRoute._addFileChildren(
    PProjectKeyRequirementsRouteChildren,
  )

interface PProjectKeyTestcasesRouteChildren {
  PProjectKeyTestcasesTestCaseIdRoute: typeof PProjectKeyTestcasesTestCaseIdRoute
  PProjectKeyTestcasesIndexRoute: typeof PProjectKeyTestcasesIndexRoute
}

const PProjectKeyTestcasesRouteChildren: PProjectKeyTestcasesRouteChildren = {
  PProjectKeyTestcasesTestCaseIdRoute: PProjectKeyTestcasesTestCaseIdRoute,
  PProjectKeyTestcasesIndexRoute: PProjectKeyTestcasesIndexRoute,
}

const PProjectKeyTestcasesRouteWithChildren =
  PProjectKeyTestcasesRoute._addFileChildren(PProjectKeyTestcasesRouteChildren)

interface PProjectKeyTestsRouteChildren {
  PProjectKeyTestsTestRunIdRoute: typeof PProjectKeyTestsTestRunIdRoute
  PProjectKeyTestsIndexRoute: typeof PProjectKeyTestsIndexRoute
}

const PProjectKeyTestsRouteChildren: PProjectKeyTestsRouteChildren = {
  PProjectKeyTestsTestRunIdRoute: PProjectKeyTestsTestRunIdRoute,
  PProjectKeyTestsIndexRoute: PProjectKeyTestsIndexRoute,
}

const PProjectKeyTestsRouteWithChildren =
  PProjectKeyTestsRoute._addFileChildren(PProjectKeyTestsRouteChildren)

interface PProjectKeyTestsuitesRouteChildren {
  PProjectKeyTestsuitesTestSuiteIdRoute: typeof PProjectKeyTestsuitesTestSuiteIdRoute
  PProjectKeyTestsuitesIndexRoute: typeof PProjectKeyTestsuitesIndexRoute
}

const PProjectKeyTestsuitesRouteChildren: PProjectKeyTestsuitesRouteChildren = {
  PProjectKeyTestsuitesTestSuiteIdRoute: PProjectKeyTestsuitesTestSuiteIdRoute,
  PProjectKeyTestsuitesIndexRoute: PProjectKeyTestsuitesIndexRoute,
}

const PProjectKeyTestsuitesRouteWithChildren =
  PProjectKeyTestsuitesRoute._addFileChildren(
    PProjectKeyTestsuitesRouteChildren,
  )

interface PProjectKeyVersionsRouteChildren {
  PProjectKeyVersionsVersionIdRoute: typeof PProjectKeyVersionsVersionIdRoute
  PProjectKeyVersionsIndexRoute: typeof PProjectKeyVersionsIndexRoute
}

const PProjectKeyVersionsRouteChildren: PProjectKeyVersionsRouteChildren = {
  PProjectKeyVersionsVersionIdRoute: PProjectKeyVersionsVersionIdRoute,
  PProjectKeyVersionsIndexRoute: PProjectKeyVersionsIndexRoute,
}

const PProjectKeyVersionsRouteWithChildren =
  PProjectKeyVersionsRoute._addFileChildren(PProjectKeyVersionsRouteChildren)
interface PProjectKeySprintsRouteChildren {
  PProjectKeySprintsSprintIdRoute: typeof PProjectKeySprintsSprintIdRoute
  PProjectKeySprintsIndexRoute: typeof PProjectKeySprintsIndexRoute
}

const PProjectKeySprintsRouteChildren: PProjectKeySprintsRouteChildren = {
  PProjectKeySprintsSprintIdRoute: PProjectKeySprintsSprintIdRoute,
  PProjectKeySprintsIndexRoute: PProjectKeySprintsIndexRoute,
}

const PProjectKeySprintsRouteWithChildren =
  PProjectKeySprintsRoute._addFileChildren(PProjectKeySprintsRouteChildren)

interface PProjectKeyRouteChildren {
  PProjectKeyAssignmentRoute: typeof PProjectKeyAssignmentRoute
  PProjectKeyBacklogRoute: typeof PProjectKeyBacklogRoute
  PProjectKeyBoardsRoute: typeof PProjectKeyBoardsRouteWithChildren
  PProjectKeyDashboardRoute: typeof PProjectKeyDashboardRoute
  PProjectKeyDefectsRoute: typeof PProjectKeyDefectsRouteWithChildren
  PProjectKeyDependenciesRoute: typeof PProjectKeyDependenciesRoute
  PProjectKeyGanttRoute: typeof PProjectKeyGanttRoute
  PProjectKeyIssuesRoute: typeof PProjectKeyIssuesRouteWithChildren
  PProjectKeyReleaseEnvironmentsRoute: typeof PProjectKeyReleaseEnvironmentsRouteWithChildren
  PProjectKeyReleasesRoute: typeof PProjectKeyReleasesRouteWithChildren
  PProjectKeyRequirementsRoute: typeof PProjectKeyRequirementsRouteWithChildren
  PProjectKeySettingsRoute: typeof PProjectKeySettingsRoute
  PProjectKeySprintsRoute: typeof PProjectKeySprintsRouteWithChildren
  PProjectKeyStatsRoute: typeof PProjectKeyStatsRoute
  PProjectKeyTestcasesRoute: typeof PProjectKeyTestcasesRouteWithChildren
  PProjectKeyTestsRoute: typeof PProjectKeyTestsRouteWithChildren
  PProjectKeyTestsuitesRoute: typeof PProjectKeyTestsuitesRouteWithChildren
  PProjectKeyTraceRoute: typeof PProjectKeyTraceRoute
  PProjectKeyVersionsRoute: typeof PProjectKeyVersionsRouteWithChildren
  PProjectKeyTraceabilityRoute: typeof PProjectKeyTraceabilityRoute
  PProjectKeyWorklogsRoute: typeof PProjectKeyWorklogsRoute
  PProjectKeyIndexRoute: typeof PProjectKeyIndexRoute
  PProjectKeyItemsItemKeyRoute: typeof PProjectKeyItemsItemKeyRoute
}

const PProjectKeyRouteChildren: PProjectKeyRouteChildren = {
  PProjectKeyAssignmentRoute: PProjectKeyAssignmentRoute,
  PProjectKeyBacklogRoute: PProjectKeyBacklogRoute,
  PProjectKeyBoardsRoute: PProjectKeyBoardsRouteWithChildren,
  PProjectKeyDashboardRoute: PProjectKeyDashboardRoute,
  PProjectKeyDefectsRoute: PProjectKeyDefectsRouteWithChildren,
  PProjectKeyDependenciesRoute: PProjectKeyDependenciesRoute,
  PProjectKeyGanttRoute: PProjectKeyGanttRoute,
  PProjectKeyIssuesRoute: PProjectKeyIssuesRouteWithChildren,
  PProjectKeyReleaseEnvironmentsRoute:
    PProjectKeyReleaseEnvironmentsRouteWithChildren,
  PProjectKeyReleasesRoute: PProjectKeyReleasesRouteWithChildren,
  PProjectKeyRequirementsRoute: PProjectKeyRequirementsRouteWithChildren,
  PProjectKeySettingsRoute: PProjectKeySettingsRoute,
  PProjectKeySprintsRoute: PProjectKeySprintsRouteWithChildren,
  PProjectKeyStatsRoute: PProjectKeyStatsRoute,
  PProjectKeyTestcasesRoute: PProjectKeyTestcasesRouteWithChildren,
  PProjectKeyTestsRoute: PProjectKeyTestsRouteWithChildren,
  PProjectKeyTestsuitesRoute: PProjectKeyTestsuitesRouteWithChildren,
  PProjectKeyTraceRoute: PProjectKeyTraceRoute,
  PProjectKeyVersionsRoute: PProjectKeyVersionsRouteWithChildren,
  PProjectKeyTraceabilityRoute: PProjectKeyTraceabilityRoute,
  PProjectKeyWorklogsRoute: PProjectKeyWorklogsRoute,
  PProjectKeyIndexRoute: PProjectKeyIndexRoute,
  PProjectKeyItemsItemKeyRoute: PProjectKeyItemsItemKeyRoute,
}

const PProjectKeyRouteWithChildren = PProjectKeyRoute._addFileChildren(
  PProjectKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  ProjectsRoute: ProjectsRoute,
  PProjectKeyRoute: PProjectKeyRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
