/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MeRouteImport } from './routes/me'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PProjectKeyRouteImport } from './routes/p/$projectKey'
import { Route as ProjectsNewRouteImport } from './routes/projects_.new'
import { Route as PProjectKeyIndexRouteImport } from './routes/p/$projectKey/index'
import { Route as PProjectKeyAssignmentRouteImport } from './routes/p/$projectKey/assignment'
import { Route as PProjectKeyBacklogRouteImport } from './routes/p/$projectKey/backlog'
import { Route as PProjectKeyDashboardRouteImport } from './routes/p/$projectKey/dashboard'
import { Route as PProjectKeyDefectsRouteImport } from './routes/p/$projectKey/defects'
import { Route as PProjectKeyDependenciesRouteImport } from './routes/p/$projectKey/dependencies'
import { Route as PProjectKeyGanttRouteImport } from './routes/p/$projectKey/gantt'
import { Route as PProjectKeyIssuesRouteImport } from './routes/p/$projectKey/issues'
import { Route as PProjectKeyReleasesRouteImport } from './routes/p/$projectKey/releases'
import { Route as PProjectKeyRequirementsRouteImport } from './routes/p/$projectKey/requirements'
import { Route as PProjectKeySettingsRouteImport } from './routes/p/$projectKey/settings'
import { Route as PProjectKeySprintsRouteImport } from './routes/p/$projectKey/sprints'
import { Route as PProjectKeyStatsRouteImport } from './routes/p/$projectKey/stats'
import { Route as PProjectKeyTestsRouteImport } from './routes/p/$projectKey/tests'
import { Route as PProjectKeyTraceRouteImport } from './routes/p/$projectKey/trace'
import { Route as PProjectKeyWorklogsRouteImport } from './routes/p/$projectKey/worklogs'
import { Route as PProjectKeyItemsItemKeyRouteImport } from './routes/p/$projectKey/items/$itemKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectKeyRoute = PProjectKeyRouteImport.update({
  id: '/p/$projectKey',
  path: '/p/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects_/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectKeyIndexRoute = PProjectKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyAssignmentRoute = PProjectKeyAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyBacklogRoute = PProjectKeyBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDashboardRoute = PProjectKeyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDefectsRoute = PProjectKeyDefectsRouteImport.update({
  id: '/defects',
  path: '/defects',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyDependenciesRoute = PProjectKeyDependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyGanttRoute = PProjectKeyGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyIssuesRoute = PProjectKeyIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyReleasesRoute = PProjectKeyReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyRequirementsRoute = PProjectKeyRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeySettingsRoute = PProjectKeySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeySprintsRoute = PProjectKeySprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyStatsRoute = PProjectKeyStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTestsRoute = PProjectKeyTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyTraceRoute = PProjectKeyTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyWorklogsRoute = PProjectKeyWorklogsRouteImport.update({
  id: '/worklogs',
  path: '/worklogs',
  getParentRoute: () => PProjectKeyRoute,
} as any)
const PProjectKeyItemsItemKeyRoute = PProjectKeyItemsItemKeyRouteImport.update({
  id: '/items/$itemKey',
  path: '/items/$itemKey',
  getParentRoute: () => PProjectKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/p/$projectKey': typeof PProjectKeyRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/p/$projectKey/assignment': typeof PProjectKeyAssignmentRoute
  '/p/$projectKey/backlog': typeof PProjectKeyBacklogRoute
  '/p/$projectKey/dashboard': typeof PProjectKeyDashboardRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsRoute
  '/p/$projectKey/dependencies': typeof PProjectKeyDependenciesRoute
  '/p/$projectKey/gantt': typeof PProjectKeyGanttRoute
  '/p/$projectKey/issues': typeof PProjectKeyIssuesRoute
  '/p/$projectKey/releases': typeof PProjectKeyReleasesRoute
  '/p/$projectKey/requirements': typeof PProjectKeyRequirementsRoute
  '/p/$projectKey/settings': typeof PProjectKeySettingsRoute
  '/p/$projectKey/sprints': typeof PProjectKeySprintsRoute
  '/p/$projectKey/stats': typeof PProjectKeyStatsRoute
  '/p/$projectKey/tests': typeof PProjectKeyTestsRoute
  '/p/$projectKey/trace': typeof PProjectKeyTraceRoute
  '/p/$projectKey/worklogs': typeof PProjectKeyWorklogsRoute
  '/p/$projectKey/': typeof PProjectKeyIndexRoute
  '/p/$projectKey/items/$itemKey': typeof PProjectKeyItemsItemKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/projects/new': typeof ProjectsNewRoute
  '/p/$projectKey/assignment': typeof PProjectKeyAssignmentRoute
  '/p/$projectKey/backlog': typeof PProjectKeyBacklogRoute
  '/p/$projectKey/dashboard': typeof PProjectKeyDashboardRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsRoute
  '/p/$projectKey/dependencies': typeof PProjectKeyDependenciesRoute
  '/p/$projectKey/gantt': typeof PProjectKeyGanttRoute
  '/p/$projectKey/issues': typeof PProjectKeyIssuesRoute
  '/p/$projectKey/releases': typeof PProjectKeyReleasesRoute
  '/p/$projectKey/requirements': typeof PProjectKeyRequirementsRoute
  '/p/$projectKey/settings': typeof PProjectKeySettingsRoute
  '/p/$projectKey/sprints': typeof PProjectKeySprintsRoute
  '/p/$projectKey/stats': typeof PProjectKeyStatsRoute
  '/p/$projectKey/tests': typeof PProjectKeyTestsRoute
  '/p/$projectKey/trace': typeof PProjectKeyTraceRoute
  '/p/$projectKey/worklogs': typeof PProjectKeyWorklogsRoute
  '/p/$projectKey': typeof PProjectKeyIndexRoute
  '/p/$projectKey/items/$itemKey': typeof PProjectKeyItemsItemKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/me': typeof MeRoute
  '/projects': typeof ProjectsRoute
  '/p/$projectKey': typeof PProjectKeyRouteWithChildren
  '/projects_/new': typeof ProjectsNewRoute
  '/p/$projectKey/assignment': typeof PProjectKeyAssignmentRoute
  '/p/$projectKey/backlog': typeof PProjectKeyBacklogRoute
  '/p/$projectKey/dashboard': typeof PProjectKeyDashboardRoute
  '/p/$projectKey/defects': typeof PProjectKeyDefectsRoute
  '/p/$projectKey/dependencies': typeof PProjectKeyDependenciesRoute
  '/p/$projectKey/gantt': typeof PProjectKeyGanttRoute
  '/p/$projectKey/issues': typeof PProjectKeyIssuesRoute
  '/p/$projectKey/releases': typeof PProjectKeyReleasesRoute
  '/p/$projectKey/requirements': typeof PProjectKeyRequirementsRoute
  '/p/$projectKey/settings': typeof PProjectKeySettingsRoute
  '/p/$projectKey/sprints': typeof PProjectKeySprintsRoute
  '/p/$projectKey/stats': typeof PProjectKeyStatsRoute
  '/p/$projectKey/tests': typeof PProjectKeyTestsRoute
  '/p/$projectKey/trace': typeof PProjectKeyTraceRoute
  '/p/$projectKey/worklogs': typeof PProjectKeyWorklogsRoute
  '/p/$projectKey/': typeof PProjectKeyIndexRoute
  '/p/$projectKey/items/$itemKey': typeof PProjectKeyItemsItemKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/me'
    | '/projects'
    | '/p/$projectKey'
    | '/projects/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/sprints'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey/'
    | '/p/$projectKey/items/$itemKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/me'
    | '/projects'
    | '/projects/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/sprints'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey'
    | '/p/$projectKey/items/$itemKey'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/me'
    | '/projects'
    | '/p/$projectKey'
    | '/projects_/new'
    | '/p/$projectKey/assignment'
    | '/p/$projectKey/backlog'
    | '/p/$projectKey/dashboard'
    | '/p/$projectKey/defects'
    | '/p/$projectKey/dependencies'
    | '/p/$projectKey/gantt'
    | '/p/$projectKey/issues'
    | '/p/$projectKey/releases'
    | '/p/$projectKey/requirements'
    | '/p/$projectKey/settings'
    | '/p/$projectKey/sprints'
    | '/p/$projectKey/stats'
    | '/p/$projectKey/tests'
    | '/p/$projectKey/trace'
    | '/p/$projectKey/worklogs'
    | '/p/$projectKey/'
    | '/p/$projectKey/items/$itemKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  MeRoute: typeof MeRoute
  ProjectsRoute: typeof ProjectsRoute
  PProjectKeyRoute: typeof PProjectKeyRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectKey': {
      id: '/p/$projectKey'
      path: '/p/$projectKey'
      fullPath: '/p/$projectKey'
      preLoaderRoute: typeof PProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/new': {
      id: '/projects_/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectKey/': {
      id: '/p/$projectKey/'
      path: '/'
      fullPath: '/p/$projectKey/'
      preLoaderRoute: typeof PProjectKeyIndexRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/assignment': {
      id: '/p/$projectKey/assignment'
      path: '/assignment'
      fullPath: '/p/$projectKey/assignment'
      preLoaderRoute: typeof PProjectKeyAssignmentRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/backlog': {
      id: '/p/$projectKey/backlog'
      path: '/backlog'
      fullPath: '/p/$projectKey/backlog'
      preLoaderRoute: typeof PProjectKeyBacklogRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/dashboard': {
      id: '/p/$projectKey/dashboard'
      path: '/dashboard'
      fullPath: '/p/$projectKey/dashboard'
      preLoaderRoute: typeof PProjectKeyDashboardRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/defects': {
      id: '/p/$projectKey/defects'
      path: '/defects'
      fullPath: '/p/$projectKey/defects'
      preLoaderRoute: typeof PProjectKeyDefectsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/dependencies': {
      id: '/p/$projectKey/dependencies'
      path: '/dependencies'
      fullPath: '/p/$projectKey/dependencies'
      preLoaderRoute: typeof PProjectKeyDependenciesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/gantt': {
      id: '/p/$projectKey/gantt'
      path: '/gantt'
      fullPath: '/p/$projectKey/gantt'
      preLoaderRoute: typeof PProjectKeyGanttRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/issues': {
      id: '/p/$projectKey/issues'
      path: '/issues'
      fullPath: '/p/$projectKey/issues'
      preLoaderRoute: typeof PProjectKeyIssuesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/releases': {
      id: '/p/$projectKey/releases'
      path: '/releases'
      fullPath: '/p/$projectKey/releases'
      preLoaderRoute: typeof PProjectKeyReleasesRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/requirements': {
      id: '/p/$projectKey/requirements'
      path: '/requirements'
      fullPath: '/p/$projectKey/requirements'
      preLoaderRoute: typeof PProjectKeyRequirementsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/settings': {
      id: '/p/$projectKey/settings'
      path: '/settings'
      fullPath: '/p/$projectKey/settings'
      preLoaderRoute: typeof PProjectKeySettingsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/sprints': {
      id: '/p/$projectKey/sprints'
      path: '/sprints'
      fullPath: '/p/$projectKey/sprints'
      preLoaderRoute: typeof PProjectKeySprintsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/stats': {
      id: '/p/$projectKey/stats'
      path: '/stats'
      fullPath: '/p/$projectKey/stats'
      preLoaderRoute: typeof PProjectKeyStatsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/tests': {
      id: '/p/$projectKey/tests'
      path: '/tests'
      fullPath: '/p/$projectKey/tests'
      preLoaderRoute: typeof PProjectKeyTestsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/trace': {
      id: '/p/$projectKey/trace'
      path: '/trace'
      fullPath: '/p/$projectKey/trace'
      preLoaderRoute: typeof PProjectKeyTraceRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/worklogs': {
      id: '/p/$projectKey/worklogs'
      path: '/worklogs'
      fullPath: '/p/$projectKey/worklogs'
      preLoaderRoute: typeof PProjectKeyWorklogsRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
    '/p/$projectKey/items/$itemKey': {
      id: '/p/$projectKey/items/$itemKey'
      path: '/items/$itemKey'
      fullPath: '/p/$projectKey/items/$itemKey'
      preLoaderRoute: typeof PProjectKeyItemsItemKeyRouteImport
      parentRoute: typeof PProjectKeyRoute
    }
  }
}

interface PProjectKeyRouteChildren {
  PProjectKeyAssignmentRoute: typeof PProjectKeyAssignmentRoute
  PProjectKeyBacklogRoute: typeof PProjectKeyBacklogRoute
  PProjectKeyDashboardRoute: typeof PProjectKeyDashboardRoute
  PProjectKeyDefectsRoute: typeof PProjectKeyDefectsRoute
  PProjectKeyDependenciesRoute: typeof PProjectKeyDependenciesRoute
  PProjectKeyGanttRoute: typeof PProjectKeyGanttRoute
  PProjectKeyIssuesRoute: typeof PProjectKeyIssuesRoute
  PProjectKeyReleasesRoute: typeof PProjectKeyReleasesRoute
  PProjectKeyRequirementsRoute: typeof PProjectKeyRequirementsRoute
  PProjectKeySettingsRoute: typeof PProjectKeySettingsRoute
  PProjectKeySprintsRoute: typeof PProjectKeySprintsRoute
  PProjectKeyStatsRoute: typeof PProjectKeyStatsRoute
  PProjectKeyTestsRoute: typeof PProjectKeyTestsRoute
  PProjectKeyTraceRoute: typeof PProjectKeyTraceRoute
  PProjectKeyWorklogsRoute: typeof PProjectKeyWorklogsRoute
  PProjectKeyIndexRoute: typeof PProjectKeyIndexRoute
  PProjectKeyItemsItemKeyRoute: typeof PProjectKeyItemsItemKeyRoute
}

const PProjectKeyRouteChildren: PProjectKeyRouteChildren = {
  PProjectKeyAssignmentRoute: PProjectKeyAssignmentRoute,
  PProjectKeyBacklogRoute: PProjectKeyBacklogRoute,
  PProjectKeyDashboardRoute: PProjectKeyDashboardRoute,
  PProjectKeyDefectsRoute: PProjectKeyDefectsRoute,
  PProjectKeyDependenciesRoute: PProjectKeyDependenciesRoute,
  PProjectKeyGanttRoute: PProjectKeyGanttRoute,
  PProjectKeyIssuesRoute: PProjectKeyIssuesRoute,
  PProjectKeyReleasesRoute: PProjectKeyReleasesRoute,
  PProjectKeyRequirementsRoute: PProjectKeyRequirementsRoute,
  PProjectKeySettingsRoute: PProjectKeySettingsRoute,
  PProjectKeySprintsRoute: PProjectKeySprintsRoute,
  PProjectKeyStatsRoute: PProjectKeyStatsRoute,
  PProjectKeyTestsRoute: PProjectKeyTestsRoute,
  PProjectKeyTraceRoute: PProjectKeyTraceRoute,
  PProjectKeyWorklogsRoute: PProjectKeyWorklogsRoute,
  PProjectKeyIndexRoute: PProjectKeyIndexRoute,
  PProjectKeyItemsItemKeyRoute: PProjectKeyItemsItemKeyRoute,
}

const PProjectKeyRouteWithChildren = PProjectKeyRoute._addFileChildren(
  PProjectKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  MeRoute: MeRoute,
  ProjectsRoute: ProjectsRoute,
  PProjectKeyRoute: PProjectKeyRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
